### ISSUE TITLE
"State" parameter is too short with @EnableOAuth2Sso

### ISSUE THREAD

**Issue by Oleg3n** [spring-guides/tut-spring-boot-oauth2#96]
Auth request from Zuul app to ORY Hydra returns "The state is missing or has less than 8 characters and is therefore considered too weak" error. The generated by spring request is like "/oauth2/auth?client_id=my-client3&redirect_uri=http://127.0.0.1:8099/login&response_type=code&scope=openid%20offline&state=bl891E" where "state" param is 5 or 6 chracters length. 
The app has 2 classes:
```java
@EnableDiscoveryClient
@EnableZuulProxy
@SpringBootApplication
public class Zuul5Application {

	public static void main(String[] args) {
		SpringApplication.run(Zuul5Application.class, args);
	}
}
```

```java
@EnableOAuth2Sso
@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.anonymous()
				.disable()
			.httpBasic()
				.disable()
			.authorizeRequests()
				.antMatchers("/login**", "/webjars/**", "/error**", "/oauth2/**")
					.permitAll()
				.anyRequest().authenticated()
			;
	}
}
```
application.yml

```yaml
zuul:
  ignoredServices: '*'
  routes:
    resourceS:
      path: /user/**
      serviceId: resS-service
      sensitiveHeaders:
      strip-prefix: true
  add-proxy-headers: true      

security:
  oauth2:
    client:
      client-id: my-client3
      client-secret: secret3
      scope:
        - openid
        - offline
      user-authorization-uri: ${app.auth-server}/oauth2/auth
      access-token-uri: ${app.auth-server}/oauth2/token
    resource:
      user-info-uri: ${app.auth-server}/userinfo
      token-info-uri: ${app.adm-server}/oauth2/introspect

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 2

```

Is something wrong with configuration?

**Comment by mohdryz** [comment]
Facing the same issue. Has this been solved for you? Below is my configuration:
````
security:
    basic:
        enabled: false
    oauth2:
        client:
            clientId: pgm-backend
            clientSecret: QYXs34SNyBAN2aLHZL6YuBOkmTnqyWQCJw==
            accessTokenUri: https://auth.************.com/oauth2/token
            userAuthorizationUri: https://auth.************.com/oauth2/auth
            redirectUri: http://localhost:9095/authorize
            scope:
              - openid
              - offline
        resource:
            userInfoUri: https://auth.************.com/userinfo
            preferTokenInfo: false
````
